### PR TITLE
Upgrade angular dependency

### PR DESCRIPTION
**Pull request by ReadyPlayerNaN**

### CODE REVIEW

**Comment by ReadyPlayerNaN** [comment]
@travelist, please set up your circle-ci, so we can see build checks on PRs.

**Comment by travelist** [comment]
@just-paja Sorry for late replying, i've just updated the CircleCI configuration! Hope now we can invoke circleCI from forked repository. Any thanks for letting me know. (also Code looks good to me, want to merge this ~if it pass the test~)

**Comment by ReadyPlayerNaN** [comment]
@travelist, I updated the PR so it would trigger tests. All green ;)

**Comment by travelist** [comment]
@just-paja LGTM! Thank you very much!:)

**Pull request merged**
