### PR TITLE
upgrade to work with angular 4+ running aot=true

### PR DESCRIPTION
**Pull request by Opticsponge**
fixes angular cli 4.0 running aot=true to [https://github.com/travelist/angular2-fontawesome/issues/28](url)

### CODE REVIEW

**Comment by vanackej** [comment]
@travelist Would you mind merging this pull request soon ? This is blocking for everyone using angular 4+

**Comment by AdrianSima** [comment]
This would solve issues #28 and #30 

But I would set dependencies like this:
`"devDependencies": {
    "@angular/common": "^2.1.0 || >=4.0.0",
    "@angular/compiler": "^2.1.0 || >=4.0.0",
    "@angular/compiler-cli": "^2.1.0 || >=4.0.0",
    "@angular/core": "^2.1.0 || >=4.0.0",

...
"peerDependencies": {
    "@angular/common": "^2.0.0 || >=4.0.0",
    "@angular/core": "^2.0.0 || >=4.0.0"
  }`
That way it would still work fine for older versions of Angular too.

**Comment by travelist** [comment]
@Opticsponge Thank you very much for this PR and sorry for late replying.
I gonna merge this PR, Thanks!

**Comment by brasycad** [comment]
Hi Travelist.

Still give this error after commit 756569a.
ERROR in /Users/*/GitHub/biddata/src/$$_gendir/node_modules/angular2-fontawesome/src/fa.component.ngfactory.ts (1,1): Property 'classList' is private and only accessible within class 'FaComponent'.
I dont understand why?

**Pull request merged**
